version: "2"

services:
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    environment:
      - SERVICE_NAME=app
    volumes:
      - "./clickfuse.com:/var/www"
    working_dir: /var/www

  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    environment:
      - SERVICE_NAME=web
    ports:
      - "8080:80"
    volumes_from:
      - app
    working_dir: /var/www
